--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

-- Started on 2024-10-10 12:01:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4816 (class 1262 OID 25545)
-- Name: accountsystem; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE accountsystem WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Spanish_Spain.1252';


ALTER DATABASE accountsystem OWNER TO postgres;

\connect accountsystem

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 25657)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    initial_balance double precision NOT NULL,
    status boolean NOT NULL,
    account_number character varying(255) NOT NULL,
    account_type character varying(255) NOT NULL,
    client_id character varying(255) NOT NULL
);


ALTER TABLE public.account OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 25664)
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    age integer NOT NULL,
    status boolean NOT NULL,
    client_id bigint NOT NULL,
    address character varying(255) NOT NULL,
    gender character varying(255) NOT NULL,
    identification character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255) NOT NULL
);


ALTER TABLE public.client OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 25553)
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    dtype character varying(31) NOT NULL,
    identification character varying(255) NOT NULL,
    address character varying(255) NOT NULL,
    age integer NOT NULL,
    gender character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    client_id bigint,
    password character varying(255),
    status boolean
);


ALTER TABLE public.person OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 25672)
-- Name: transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction (
    amount double precision NOT NULL,
    balance double precision NOT NULL,
    transaction_date date NOT NULL,
    id bigint NOT NULL,
    account_number character varying(255) NOT NULL,
    transaction_type character varying(255) NOT NULL
);


ALTER TABLE public.transaction OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 25671)
-- Name: transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4807 (class 0 OID 25657)
-- Dependencies: 218
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.account VALUES (1000, true, '585545', 'Corriente', '1234567890');
INSERT INTO public.account VALUES (5000, true, '585590', 'Ahorros', '1234567893');
INSERT INTO public.account VALUES (1425, true, '478758', 'Ahorros', '1234567890');
INSERT INTO public.account VALUES (700, true, '225487', 'Corriente', '1234567891');
INSERT INTO public.account VALUES (250, true, '495878', 'Ahorros', '1234567892');
INSERT INTO public.account VALUES (400, true, '496825', 'Ahorros', '1234567891');


--
-- TOC entry 4808 (class 0 OID 25664)
-- Dependencies: 219
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.client VALUES (30, true, 1, 'Otavalo sn y principal', 'M', '1234567890', 'Jose Lema', '1234', '098254785');
INSERT INTO public.client VALUES (25, true, 2, 'Amazonas y NNUU', 'F', '1234567891', 'Marianela Montalvo', '5678', '097548965');
INSERT INTO public.client VALUES (53, true, 3, '13 junio y Equinoccial', 'M', '1234567892', 'Juan Osorio', '1245', '098874587');
INSERT INTO public.client VALUES (31, true, 4, 'Ponceano Alto', 'M', '1234567893', 'Eduardo Reyes', '4567', '098874588');


--
-- TOC entry 4806 (class 0 OID 25553)
-- Dependencies: 217
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4810 (class 0 OID 25672)
-- Dependencies: 221
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.transaction VALUES (-575, 1425, '2022-02-10', 1, '478758', 'R');
INSERT INTO public.transaction VALUES (600, 700, '2022-02-10', 2, '225487', 'D');
INSERT INTO public.transaction VALUES (150, 250, '2022-02-10', 3, '495878', 'D');
INSERT INTO public.transaction VALUES (-540, 0, '2022-02-08', 4, '496825', 'R');
INSERT INTO public.transaction VALUES (400, 400, '2022-02-08', 5, '496825', 'D');


--
-- TOC entry 4817 (class 0 OID 0)
-- Dependencies: 220
-- Name: transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_id_seq', 5, true);


--
-- TOC entry 4656 (class 2606 OID 25663)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_number);


--
-- TOC entry 4658 (class 2606 OID 25670)
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (identification);


--
-- TOC entry 4654 (class 2606 OID 25559)
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (identification);


--
-- TOC entry 4660 (class 2606 OID 25678)
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (id);


-- Completed on 2024-10-10 12:01:55

--
-- PostgreSQL database dump complete
--

